const ACTIONS = Object.freeze({
  LOADING_PROJECTS: "LOADING_PROJECTS",
  PROJECTS_LOADED: "PROJECTS_LOADED",

  LOADING_CERTIFICATES: "LOADING_CERTIFICATES",
  CERTIFICATES_LOADED: "CERTIFICATES_LOADED",

  LOADING_WORKEXPERIENCES: "LOADING_WORKEXPERIENCES",
  WORKEXPERIENCES_LOADED: "WORKEXPERIENCES_LOADED",

  LOADING_SKILLS: "LOADING_SKILLS",
  SKILLS_LOADED: "SKILLS_LOADED",

  LOADING_EDUCATIONS: "LOADING_EDUCATIONS",
  EDUCATIONS_LOADED: "EDUCATIONS_LOADED",

  LOADING_USER: "LOADING_USER",
  USER_LOADED: "USER_LOADED",
});

export { ACTIONS };
