const ACTIONS = Object.freeze({
  LOADING_PROJECTS: "LOADING_PROJECTS",
  PROJECTS_LOADED: "PROJECTS_LOADED",

  LOADING_CERTIFICATES: "LOADING_CERTIFICATES",
  CERTIFICATES_LOADED: "CERTIFICATES_LOADED",
});

export { ACTIONS };
